# .github/workflows/load-data.yml


name: 'Cargar datos a PostgreSQL'


on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/load_data.py'
      - 'data/IndianFlightdata - Sheet1.csv'

jobs:
  load-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas psycopg2-binary

      - name: Run data load script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: python scripts/load_data.py